#!/usr/bin/env python
from setuptools import setup, find_packages

setup (
    name='lovely.memcached',
    version='0.1.0',
    author = "Lovely Systems",
    author_email = "office@lovelysystems.com",
    description = "A memcached client utiltiy for zope 3",
    license = "ZPL 2.1",
    keywords = "zope3 zope memcached cache ram",
    url = 'svn://svn.zope.org/repos/main/lovely.memcached',
    packages = find_packages('src'),
    include_package_data = True,
    package_dir = {'':'src'},
    namespace_packages = ['lovely'],
    extras_require = dict(test = ['z3c.configurator',
                                  'z3c.testing',
                                  'zope.app.keyreference',
                                  'zope.app.securitypolicy',
                                  'zope.app.testing',
                                  'zope.app.zcmlfiles',
                                  'z3c.testing',
                                  'zope.testbrowser',
                                  ]),
    install_requires = ['setuptools',
                        'python-memcached',    
                        'zope.app.component',
                        'zope.app.intid',
                        'zope.event',
                        'zope.interface',
                        'zope.lifecycleevent',
                        'zope.schema',
                        'zope.security'
                        ],
    zip_safe = False,
    )
